PUBLIC CLASES CLASE {   
}
TODO LO QUE VALLA DENTRO DE ESAS LLAVES SON LOS MIEMBROS DE LA CLASE 
PARA COLOCAR LA CLASER A FUERZAS DEBE SER VOID MAN  Y LA RAYA STRING SON LAS OPCIONES DE EJECUCUON DE LAS QUE HAYAS PASADO

SIEMPRE LA PUERTA DE ENTRADA A JAVA ES EL METODO MAIN AUNADO A VOID 
JAVA ESTA COMPUESTA DE TRES COSAS EL LENGUAJE JV , LA APY DE JAVA QUE SON LAS LIBRERIA Y LA TERCERA LA MAQUINA VIRTUAL DE JAVA QUE ES LA SOLUCIÓN O PROCESO QUE SE INSTALA EN LAS MÁQUINAS QUE SE NECESITA REALIZAR SOBRE UNA MAQUINA VIRTUAL INTERPRETANDOLO EN JAVA


EJEMPLO 
PUBLIC CLASS HOLA MUNDO{
PUBLIC STATIC VOID MAN (STRING[] ARGS) {
SYSTEM.OUT.PRINTLN("¡HOLA MUNDO!");
}
}
DESPUES SE COMPILA PARA PODER EJECUTARLA

el jdk contiene la serier de librerias y otra cosa que incluye es el compilador de java

